---
hostname: "ticketsystem.{{ tailscale_domain }}"
zammad_compose_dir: /opt/zammad-docker-compose
zammad_compose_version: a1feeee
docker_service_enabled: true
software_groups_to_install:
  - admin
  - editors
  - utils
