---
- name: Add Google Cloud SDK repo
  ansible.builtin.yum_repository:
    name: google-cloud-cli
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: false
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    file: google-cloud-sdk

- name: Install google-cloud-cli
  ansible.builtin.package:
    name: google-cloud-cli
    state: present

- name: Ensure /opt/kui directory exists
  ansible.builtin.file:
    path: /opt/kui
    state: directory
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_group.name }}"
    mode: '0755'

- name: Copy KUI script
  ansible.builtin.copy:
    src: kui.sh
    dest: /opt/kui/kui.sh
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_group.name }}"
    mode: '0755'

- name: Run KUI script monthly
  ansible.builtin.cron:
    name: Run KUI script
    job: /opt/kui/kui.sh
    day: "1"
    hour: "0"
    minute: "0"
    user: galaxy
