---
- name: include rabbitmq installation tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}/install.yml"

- ansible.builtin.include_tasks: configure.yml

- ansible.builtin.include_tasks: configure-cluster.yml
  when: rabbitmq_cluster

- name: start rabbitmq server
  service:
    name: rabbitmq-server
    enabled: True
    state: started

- ansible.builtin.include_tasks: vhosts.yml

- ansible.builtin.include_tasks: users.yml

- ansible.builtin.include_tasks: plugins.yml

- ansible.builtin.include_tasks: cluster.yml
  when: rabbitmq_cluster and rabbitmq_nodename != rabbitmq_cluster_master
