---
- name: Manage authorized SSH keys
  hosts: all
  gather_facts: true
  roles:
    - role: usegalaxy_eu.ssh_manager
    - role: rocky_security_repository
      become: true
      when: ansible_facts['distribution'] == "Rocky"
