---
- name: Tasks for "base environment" hosts
  hosts: infrastructure
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - dev-sec.os-hardening
    - geerlingguy.pip
    - dj-wasabi.telegraf
    - jnv.unattended-upgrades



  #pre_tasks:
    #- name: Locate secret group variable files
      #local_action:
        #module: stat
        #path: "{{ inventory_dir }}/secret_group_vars/{{ item }}.yml"
      #become: no
      #with_items: "{{ group_names }}"
      #register: secret_group_vars
      #tags: always
    #- name: Include secret group variables
      #local_action:
        #module: "include_vars {{ item.stat.path }}"
      #become: no
      #with_items: "{{ secret_group_vars.results }}"
      #when: item.stat.exists
      #tags: always
#  roles:
#    - role: requiretty        # Disable requiretty for Ansible ssh pipelining
#      tags: initial,requiretty
#    - role: remote_management # Set up IPMI/serial stuff
#      tags: initial,remote_management
#    - role: ssh               # Enable password auth and root logins
#      tags: initial,ssh
#    - role: timezone          # Configure system timezone
#      tags: initial,timezone
#    - role: resolv            # Set resolv.conf for static hosts
#      tags: initial,resolv
#    - role: packages          # Install packages
#      tags: system,packages
#    - role: users             # Create users and set up authentication keys
#      tags: system,users
#    - role: paths             # Configure path permissions, filesystems
#      tags: system,paths
#    - role: copy              # Copy arbitrary files/templates
#      tags: system,copy
#    - role: cron              # Create cron jobs
#      tags: system,cron
#    - role: firewall          # Configure host firewall
#      tags: system,firewall
#    - role: services          # Manage services
#      tags: system,services
#    # Most baseenv hosts will want mail config
#    - role: postfix           # MX and null client configuration
#      tags: mail,postfix
#      when: "'baseenv-nomail' not in group_names"
#    # This is in the baseenv play for a reason I think, but what's the reason? -nate
#    - role: mailman           # Mailing lists
#      tags: mail,mailman
#      when: "'listservers' in group_names"
#  tags: initial,baseenv
#
## This is sort of ugly - we don't want to use the galaxyenv basenv for
## jetstream controllers because they are controlled in the jetstream envs. All
## this is used for currently is setting up the `swarm` system user.
#- name: Initial setup for docker swarm managers
#  hosts: dockerswarmmanagers
#  remote_user: root
#  vars_files:
#    - secret_group_vars/all.yml
#    - secret_group_vars/dockerswarmmanagers.yml
#  roles:
#    - role: users
#      tags: users
#  tags: initial
#
## This play is currently Debuntu-only
#- name: Tasks for "lite environment" hosts (Kerberos/LDAP/NFS, no AFS)
#  hosts: liteenv
#  remote_user: root
#  vars_files:
#    - "secret_group_vars/all.yml"
#    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
#  roles:
#    - role: kerberos
#      tags: kerberos
#    # Run the ssh role again here because doing so with the liteenv group will
#    # enable GSSAPIAuthentication
#    - role: ssh
#      tags: ssh
#    - role: ldap
#      tags: ldap
#    - role: nfs
#      tags: nfs
#  tags: liteenv
#
#- name: Tasks for webservers
#  hosts: webservers
#  remote_user: root
#  vars_files:
#    - "secret_group_vars/sslwebservers.yml"
#  roles:
#    - role: galaxyprojectdotorg.nginx
#      tags: nginx
#
#- name: Install supervisor
#  hosts: all
#  remote_user: root
#  roles:
#    - role: supervisor
#      when: supervisord_group_configs is defined or supervisord_host_configs is defined
#      tags: supervisor,services
#
#- name: Tasks for jenkins hosts
#  hosts: jenkinsservers
#  remote_user: root
#  roles:
#    - role: linuxbrew        # Install linuxbrew
#      tags: linuxbrew
#  tags: initial
#
#- name: Tasks for biostar hosts
#  hosts: biostarservers
#  vars_files:
#    - "secret_group_vars/all.yml"
#    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
#  roles:
#    - role: users
#      tags: system,users
#  tags: initial
#
## This is here because it's currently due to a SmartOS issue:
## https://github.com/joyent/smartos-live/issues/469
## If that issue is fixed, it should be possible to remove this and undo
## explicitly setting the sys_fs_import priv
#- name: Assign the sys_fs_import privilege to backup users
#  hosts: zfsbackupservers
#  remote_user: root
#  vars:
#    backupusers:
#      - zfsdump-orval
#  tasks:
#    - name: "Set sys_fs_import for backup users"
#      lineinfile:
#        dest: /etc/user_attr
#        backup: "yes"
#        line: "{{ item }}::::type=normal;defaultpriv=basic,sys_fs_import"
#        regexp: "^{{ item }}:.*"
#      with_items: backupusers
#
#- name: Tasks for CVMFS Servers
#  hosts: cvmfsstratum0servers:cvmfsstratum1servers:cvmfslocalproxies
#  vars_files:
#    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
#    # FIXME: required for cvmfs1-psu0 since the cvmfs role depends on the docker role and that host is also a docker swarm manager
#    - secret_group_vars/dockersslservers.yml
#  roles:
#    # mounts /srv
#    - role: paths
#      tags: cvmfs
#    # need epel for the jq package
#    - role: geerlingguy.repo-epel
#      tags: cvmfs
#    - role: cvmfs
#      tags: cvmfs
#
#- name: Tasks for Docker Swarm managers
#  hosts: dockerswarmmanagers
#  vars_files:
#    - "secret_group_vars/dockersslservers.yml"
#  roles:
#    - role: docker_swarm
#      tags: docker
