---
- name: Tasks for "jenkins" hosts
  hosts: build
  become: true
  vars:
    hostname: build.galaxyproject.eu
  vars_files:
    - "secret_group_vars/jenkins.yml"
    - "secret_group_vars/all.yml"
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['policycoreutils-python']
      become: yes
  roles:
    #- hostname
    #- usegalaxy-eu.dynmotd
    #- geerlingguy.repo-epel
    #- hxr.admin-tools
    #- influxdata.chrony
    #- hxr.monitor-email
    #- linuxhq.yum_cron
    #- galaxyproject.nginx
    #- ssh-host-sign
    ##- hxr.autofs-format-n-mount
    ## CUSTOM
    #- geerlingguy.java
    - geerlingguy.jenkins
    #- usegalaxy-eu.jenkins-ssh-key
    ### END CUSTOM
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
