---
- name: Tasks for "jenkins" hosts
  hosts: build
  become: true
  vars:
    hostname: build.galaxyproject.eu
    playbook_secret_vars_files:
      - secret_group_vars/jenkins.yml
      - secret_group_vars/all.yml
  pre_tasks:
    - name: Load secret variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop: "{{ playbook_secret_vars_files }}"
      no_log: true
    - name: Install Dependencies
      ansible.builtin.package:
        enablerepo: crb
        name: ["policycoreutils-python-utils", "python3-wheel-wheel"]
      become: true
    - name: Permit traffic in default zone for HTTP and HTTPS service
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - usegalaxy-eu.autoupdates
    - galaxyproject.nginx
    - ssh-host-sign
    # - hxr.autofs-format-n-mount
    # CUSTOM
    - geerlingguy.java
    - geerlingguy.jenkins
    - usegalaxy-eu.jenkins-ssh-key
    ## END CUSTOM
    - dj-wasabi.telegraf
    - galaxyproject.miniconda
    - devsec.hardening.os_hardening
    # - nginx_hardening
    - devsec.hardening.ssh_hardening
