---
- hosts: cvmfsstratum1servers
  become: true
  vars:
    hostname: cvmfs1-ufr0.bi.privat
  vars_files:
    - "secret_group_vars/all.yml"
    - mounts/mountpoints.yml
    - mounts/dest/all.yml
  collections:
    - devsec.hardening
  pre_tasks:
    - file:
        src: /data/dnb01
        dest: /srv
        owner: root
        group: root
        state: link
        force: true
    - name: Replace all `cvmfs0-tacc0.galaxyproject.org` references with `cvmfs0-psu1.galaxyproject.org` in role defaults
      # workaround until https://github.com/galaxyproject/ansible-cvmfs/pull/93 is merged
      ansible.builtin.set_fact:
        galaxy_cvmfs_repositories: >-
          {%- set ns = namespace(out=[]) -%}
          {%- for repo in galaxy_cvmfs_repositories -%}
          {%-   set _ = ns.out.append(
                  repo | combine({'stratum0': 'cvmfs0-psu1.galaxyproject.org'})
                  if repo.stratum0 | default('') == 'cvmfs0-tacc0.galaxyproject.org'
                  else repo
                ) -%}
          {%- endfor -%}
          {{- ns.out -}}
  post_tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
      register:
        selinux_disabled
  roles:
    # Starting configuration of the operating system
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_hostname: true
        enable_powertools: true        # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_grub: true
        enable_kernel_5: true
    - geerlingguy.repo-epel     # Install EPEL repository
    - influxdata.chrony         # Keep our time in sync.
    - usegalaxy-eu.dynmotd
    # Filesystems
    - usegalaxy-eu.autofs
    # Applications
    - galaxyproject.cvmfs
    - hxr.monitor-squid
    - hxr.monitor-cvmfs
    - dj-wasabi.telegraf
    # hardening
    # - os_hardening
    # - ssh_hardening

#
#    - hostname
#    - usegalaxy-eu.dynmotd
#    - geerlingguy.repo-epel
#    - hxr.admin-tools
#    - influxdata.chrony
#    - hxr.monitor-email
#    - linuxhq.yum_cron
#    - hxr.autofs
#    # BEGIN custom
#    - galaxyproject.cvmfs
#    - hxr.monitor-squid
#    - hxr.monitor-cvmfs
#    # END custom
#    - dj-wasabi.telegraf
#    - dev-sec.os-hardening
#    - dev-sec.ssh-hardening
