---
- name: DNBD3 Infrastructure
  hosts: dnbd3primary,dnbd3proxy
  become: true
  pre_tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - git
        state: present

    - name: Create dnbd3 user
      ansible.builtin.group:
        name: "{{ dnbd3_group }}"
        state: present
    - name: Create dnbd3 user
      ansible.builtin.user:
        name: "{{ dnbd3_user }}"
        group: "{{ dnbd3_group }}"
        shell: /bin/false
        create_home: false
    - name: Grant access to dnbd3 root directory
      ansible.builtin.file:
        mode: "770"
        path: "{{ dnbd3_base_path }}"
        state: directory
        owner: "{{ dnbd3_user }}"
        group: "{{ dnbd3_group }}"
    - name: Grant access to tftp root directory
      ansible.builtin.file:
        mode: "770"
        path: "{{ tftpboot_path }}"
        state: directory
        owner: "{{ tftp_user }}"
        group: "{{ tftp_group }}"
      when: "'dnbd3primary' in group_names"
  roles:
    #    - role: usegalaxy_eu.handy.os_setup
    #      become: true
    #      vars:
    #        hostname: "{{ inventory_hostname }}"
    #        enable_hostname: true
    #        enable_powertools: true
    #      when: "'dnbd3_primary' in group_names"
    - role: usegalaxy_eu.dnbd3
    - role: usegalaxy_eu.tftp
      when: "'dnbd3primary' in group_names"
    - role: geerlingguy.apache
      when: "'dnbd3primary' in group_names"


  post_tasks:
    - name: Grant access to http directory
      ansible.builtin.file:
        mode: "770"
        path: "{{ apache_vhosts[0].documentroot }}"
        state: directory
        owner: "www-data"
        group: "www-data"
      when: "'dnbd3primary' in group_names"
