---
- name: DNBD3 Infrastructure
  hosts: dnbd3primary,dnbd3proxy
  become: true
  vars_files:
    - secret_group_vars/all.yml

  pre_tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - git
        state: present
    - name: Create dnbd3 user
      ansible.builtin.group:
        name: "{{ dnbd3_group }}"
        state: present
    - name: Create dnbd3 user
      ansible.builtin.user:
        name: "{{ dnbd3_user }}"
        group: "{{ dnbd3_group }}"
        shell: /bin/false
        create_home: false
    - name: Grant access to dnbd3 root directory
      ansible.builtin.file:
        mode: "770"
        path: "{{ dnbd3_base_path }}"
        state: directory
        owner: "{{ dnbd3_user }}"
        group: "{{ dnbd3_group }}"

  post_tasks:
    - name: Create SELinux rule for apache to access http dir
      community.general.sefcontext:
        target: '{{ dnbd3_base_path }}/http(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
    - name: Make autofs RequiredBy tftp, httpd, dnbd3
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Make sure services that depend on autofs only start once it is up
          Requires=autofs.service
          After=autofs.service
          Before=tftp.service dnbd3-server.service httpd.service
          StartLimitIntervalSec=200
          StartLimitBurst=5
          [Service]
          Restart=always
          RestartSec=15
          Type=oneshot
          ExecStart=/bin/ls "{{ dnbd3_base_path }}"
          [Install]
          RequiredBy=tftp.service dnbd3-server.service httpd.service
        dest: /etc/systemd/system/require-autofs.service
    - name: Enable the service
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: started
        enabled: true
        name: require-autofs.service

  roles:
    - usegalaxy-eu.dynmotd
    - usegalaxy-eu.autoupdates # keep all of our packages up to date
    - influxdata.chrony # Keep our time in sync.
    - dj-wasabi.telegraf
    - role: usegalaxy-eu.autofs
      when: "'dnbd3primary' in group_names"
    - role: usegalaxy_eu.handy.os_setup
      vars:
        hostname: "{{ inventory_hostname }}"
        enable_hostname: true
        enable_powertools: true
      when: "'dnbd3_primary' in group_names"
    - role: usegalaxy_eu.dnbd3
    - role: usegalaxy_eu.tftp
      when: "'dnbd3primary' in group_names"
    - role: geerlingguy.apache
      when: "'dnbd3primary' in group_names"
    - role: usegalaxy_eu.dnbd3-primary
      when: "'dnbd3primary' in group_names"
    - role: usegalaxy_eu.firewall
