---
- name: Incoming
  hosts: incoming
  become: true
  vars:
    hostname: incoming.galaxyproject.eu
  vars_files:    
    - secret_group_vars/all.yml
  collections:
    - devsec.hardening
  pre_tasks:
    - name: Set timezone to Europe/Berlin
      community.general.timezone:
        name: Europe/Berlin
    - name: Install Dependencies
      package:
        name: [ 'postgresql', 'proftpd-utils' ]
    - name: Configure SELinux
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - ftpd_full_access
        - ftpd_connect_db
        - ftpd_use_passive_mode
  post_tasks:
    - name: Replace sql
      ansible.builtin.replace:
        path: /etc/proftpd.conf.d/10_galaxy_auth.conf
        regexp: 'galaxy_user'
        replace: "galaxy.galaxy_user"
      notify:
        - reload proftpd
    - name: Enable Dynamic ban lists
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/proftpd
        regexp: '^PROFTPD_OPTIONS='
        line: PROFTPD_OPTIONS="-DDYNAMIC_BAN_LISTS"
      notify:
        - reload proftpd
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - usegalaxy-eu.autoupdates

    # User
    - usegalaxy-eu.remap-user
    - usegalaxy-eu.create-user

    # Filesystems
    - usegalaxy-eu.autofs

    # Services
    - galaxyproject.nginx
    - galaxyproject.proftpd

    - dj-wasabi.telegraf
    - os_hardening
    - ssh_hardening
    
