---
- hosts: influxdb
  become: true
  vars:
    hostname: influxdb.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python-requests', 'python3-virtualenv', 'python36']
      become: yes
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    - hxr.autofs
    # BEGIN custom
    - usegalaxy_eu.influxdb
    - hxr.influxdb
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
