---
- hosts: job-working-dir
  become: true
  vars:
    hostname: job-working-dir.internal.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - hxr.autofs
    # BEGIN custom
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
