---
- name: Plausible
  hosts: plausible
  become: true
  vars:
    hostname: plausible.galaxyproject.eu
  vars_files:
    - secret_group_vars/all.yml
    - secret_group_vars/plausible.yml
  collections:
    - devsec.hardening
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - usegalaxy-eu.autoupdates
    - galaxyproject.nginx
    # missing iptables, pip3 install docker
    - geerlingguy.docker
    # Custom
    - usegalaxy-eu.plausible
    # End Custom
    - dj-wasabi.telegraf
    #- os_hardening
    #- nginx_hardening
    #- ssh_hardening
