---
- name: Proxy
  hosts: proxy
  become: true
  vars:
    hostname: proxy.galaxyproject.eu
  vars_files:
    - group_vars/all.yml
    - secret_group_vars/all.yml
  collections:
    - devsec.hardening
  pre_tasks:
    - name: Set default version of Python
      alternatives:
        name: python
        path: /usr/bin/python3
  roles:
    # Starting configuration of the operating system
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_hostname: true
        enable_powertools: true        # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_grub: true
    - geerlingguy.repo-epel     # Install EPEL repository
    - usegalaxy-eu.autoupdates  # keep all of our packages up to date
    - influxdata.chrony         # Keep our time in sync.
    - usegalaxy-eu.dynmotd
    # Applications
    - galaxyproject.nginx
    - dj-wasabi.telegraf
    # hardening
    - os_hardening
    - ssh_hardening




#
#    - hostname
#    - usegalaxy-eu.dynmotd
#    - geerlingguy.repo-epel
#    - hxr.admin-tools
#    - influxdata.chrony
#    - hxr.monitor-email
#    - linuxhq.yum_cron
#    - jasonroyle.rabbitmq
#    - galaxyproject.nginx
#    - dj-wasabi.telegraf
    # - os_hardening
    # - nginx_hardening
    # - ssh_hardening
