---
collections:
  - name: amazon.aws
    version: 1.5.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: community.docker
    version: 1.9.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: community.grafana
    version: 1.2.1
    source: https://galaxy.ansible.com
    type: galaxy
  - name: community.rabbitmq
    version: 1.1.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: devsec.hardening
    version: 8.3.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: usegalaxy_eu.handy
    version: 2.10.0
    source: https://galaxy.ansible.com

roles:
  - name: dev-sec.os-hardening
    version: 4.2.0
  - name: dev-sec.ssh-hardening
    version: 9.7.0
  - name: devops.tomcat7
    version: 1.0.0
    # - name: dj-wasabi.telegraf
    #  version: 0.10.0
  - name: galaxyproject.galaxy
    src: https://github.com/galaxyproject/ansible-galaxy
    version: 0.9.18
  - name: galaxyproject.cvmfs
    src: https://github.com/usegalaxy-eu/ansible-cvmfs
    version: master
  - name: galaxyproject.proftpd
    version: 0.3.2
  - name: usegalaxy_eu.ansible_nginx_upload_module
    version: 1.0.0
  - name: usegalaxy-eu.nginx
    src: https://github.com/usegalaxy-eu/ansible-nginx
    version: master
  - name: galaxyproject.nginx
    version: 0.6.4
  - name: galaxyproject.postgresql
    version: 1.1.0
  - name: usegalaxy-eu.ansible-postgresql
    src: https://github.com/usegalaxy-eu/ansible-postgresql
    version: main
  - name: geerlingguy.docker
    version: 4.1.1
  - name: geerlingguy.java
    version: 1.9.5
  - name: geerlingguy.jenkins
    version: 4.3.0
  - name: geerlingguy.repo-epel
    version: 3.1.0
  - name: influxdata.chrony
    src: https://github.com/usegalaxy-eu/ansible-chrony
    version: 0.1.0
  - name: linuxhq.yum_cron
    version: master
  - name: galaxyproject.gxadmin
    version: 0.0.8
  - name: usegalaxy-eu.certbot
    src: https://github.com/usegalaxy-eu/ansible-certbot
    version: 0.1.5
  - name: usegalaxy_eu.galaxy_systemd
    version: 2.0.0
  - name: usegalaxy-eu.dynmotd
    src: https://github.com/usegalaxy-eu/ansible-dynmotd
    version: 0.0.1
  - name: cloudalchemy.grafana
    version: 0.16.2
  - name: galaxyproject.tiaas2
    version: 2.1.3
  - name: usegalaxy-eu.autoupdates
    src: https://github.com/usegalaxy-eu/ansible-autoupdates
    version: 0.0.1
  - name: usegalaxy_eu.htcondor
    version: 1.0.1
  - name: usegalaxy-eu.update-hosts
    src: https://github.com/usegalaxy-eu/ansible-update-hosts
    version: 0.2.0
  - name: usegalaxy_eu.gie_proxy
    version: 0.0.2
  - name: usegalaxy-eu.autofs
    src: https://github.com/usegalaxy-eu/ansible-autofs
    version: 1.0.0
  - name: usegalaxy_eu.fs_maintenance
    version: 0.0.5
  - name: galaxyproject.tusd
    version: 0.0.1
  - name: usegalaxy_eu.rabbitmqserver
    version: 1.4.1
  - name: usegalaxy_eu.influxdbserver
    version: 1.1.1
  - name: usegalaxy_eu.flower
    version: 0.3.1-alpha
  - name: paprikant.beacon
    src: https://github.com/Paprikant/ansible-role-beacon
  - name: paprikant.beacon-importer
    src: https://github.com/Paprikant/ansible-role-beacon_importer
  - name: galaxyproject.miniconda
    version: 0.3.1
  - name: usegalaxy_eu.tpv_auto_lint
    version: 0.2.1
