---
- name: UseGalaxy EU maintenance server
  hosts: maintenance
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/all.yml
    - group_vars/maintenance.yml
  roles:
    - l3d.restic
