---
- name: Tasks for cvmfs-nfs-preload hosts
  hosts: cvmfspreload
  become: true
  vars:
    hostname: cvmfs1-ufr1-nfs.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - geerlingguy.repo-epel
    - cvmfs
    - hxr.admin-tools
    - dj-wasabi.telegraf
    - geerlingguy.nfs
    - linuxhq.yum_cron
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
