---
- hosts: telescope
  become: true
  vars:
    hostname: telescope.internal.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  pre_tasks:
    - package:
        name: ['python-psycopg2']
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    - hxr.autofs
    # BEGIN custom
    - usegalaxy-eu.gxadmin
    - usegalaxy-eu.galactic-radio-telescope
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
