---
- name: Configure firewall
  become: true
  hosts: traefik
  tasks:
    - name: Ensure IPv4 forwarding is enabled
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: true

    - name: Allow access to Traefik entry points
      ansible.posix.firewalld:
        port: "{{ item.port | default(omit) }}"
        service: "{{ item.service | default(omit) }}"
        permanent: true
        immediate: true
        zone: public
        state: enabled
      loop:
        - service: ssh
        - service: amqps
        - service: http
        - service: https
        - service: ntp
        - service: ftp  # passive ports are not managed by Traefik
        - port: 9087/tcp  # CVMFS rsync port

    - name: Configure passive FTP port forwarding
      vars:
        ftp_node_hostname: "{{ groups['incoming'][0] }}"
        ftp_node_address: "{{ hostvars[ftp_node_hostname].ansible_host }}"
      block:
        - name: Read existing firewall rules
          ansible.builtin.shell: "firewall-cmd --permanent --direct --get-all-rules | grep '{{ ftp_firewall_rules_tag }}'"
          register: ftp_firewall_rules_existing
          failed_when: false
          changed_when: false
          check_mode: false

        - name: Delete existing firewall rules
          # no service interruption, changes will be applied on next reload
          ansible.builtin.shell: "firewall-cmd --permanent --direct --remove-rule {{ item }}"
          when: ftp_firewall_rules_existing.stdout_lines | length > 0
          loop: "{{ ftp_firewall_rules_existing.stdout_lines }}"
          loop_control:
            label: "{{ item }}"
          changed_when: false

        - name: Create new firewall rules
          ansible.builtin.command: >-
            firewall-cmd --permanent --direct --add-rule {{ item.rule }}
            -m comment --comment "{{ ftp_firewall_rules_tag }}_{{ item.name }}"
          loop:
            - name: FORWARD
              rule: "ipv4 nat PREROUTING 0 -d {{ ansible_default_ipv4.address }} -p tcp --dport {{ ftp_passive_ports.replace('-', ':') }} -j DNAT --to-destination {{ ftp_node_address }}"
            - name: MASQUERADE
              rule: "ipv4 nat POSTROUTING 0 -d {{ ftp_node_address }} -p tcp --dport {{ ftp_passive_ports.replace('-', ':') }} -j MASQUERADE"
            - name: FORWARD_PATH
              rule: "ipv4 filter FORWARD 0 -d {{ ftp_node_address }} -p tcp --dport {{ ftp_passive_ports.replace('-', ':') }} -j ACCEPT"
            - name: RETURN_PATH
              rule: "ipv4 filter FORWARD 0 -s {{ ftp_node_address }} -p tcp --sport {{ ftp_passive_ports.replace('-', ':') }} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"
          loop_control:
            label: "{{ item.name }}"
          changed_when: false

        - name: Read configured firewall rules
          ansible.builtin.shell: >-
            firewall-cmd
            --permanent
            --direct
            --get-all-rules
            | grep "{{ ftp_firewall_rules_tag }}"
          register: ftp_firewall_rules_configured
          changed_when: false
          when: not ansible_check_mode
          check_mode: false

        - name: Determine whether firewall rules have changed
          ansible.builtin.set_fact:
            ftp_firewall_rules_changed: >-
              {{
                ftp_firewall_rules_existing.stdout_lines | difference(ftp_firewall_rules_configured.stdout_lines) | length > 0
                or
                ftp_firewall_rules_configured.stdout_lines | difference(ftp_firewall_rules_existing.stdout_lines) | length > 0
              }}
          changed_when: false
          when: not ansible_check_mode

        - name: Apply firewall configuration changes
          ansible.builtin.command: "firewall-cmd --reload"
          when: ftp_firewall_rules_changed is defined and ftp_firewall_rules_changed
          changed_when: true

- name: Traefik
  become: true
  hosts: traefik
  vars_files:
    - secret_group_vars/all.yml
    - secret_group_vars/traefik.yml
    - secret_group_vars/keys.yml
  pre_tasks:
    - name: Install ansible dependencies
      ansible.builtin.package:
        name: "{{ item }}"
      with_items:
        - python3-policycoreutils
        - python3-libselinux
        - policycoreutils-python-utils
        - python3-pip

    - name: Install python docker
      become: true
      ansible.builtin.pip:
        name: "{{ item }}"
        virtualenv_command: "python3 -m venv"
      loop:
        - docker
        - selinux

    - name: Copy Galaxy active users script
      ansible.builtin.copy:
        src: files/traefik/active_users.sh
        dest: "{{ galaxy_active_users_script }}"
        mode: '0755'
        owner: root
        group: root

  roles:
    - geerlingguy.repo-epel # Install EPEL repository
    - influxdata.chrony # Keep our time in sync.
    - dj-wasabi.telegraf
    - usegalaxy-eu.logrotate # Rotate logs
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_hostname: true
        enable_powertools: true # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_remap_user: false
        enable_exclude_packages: true
        enable_pam_limits: true # Prevent out of control processes
        enable_install_software: true # Some extra admin tools (*top, vim, etc)
    - usegalaxy-eu.dynmotd
    - artis3n.tailscale
    - usegalaxy_eu.traefik
    - devsec.hardening.ssh_hardening
    - devsec.hardening.os_hardening
