---
- name: Tasks for "ubuntu" hosts
  hosts: ubuntu
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - hxr.vault
    - influxdata.chrony
    - jnv.unattended-upgrades
    - hxr.admin-tools
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
