# - name: Import sn10 playbook
#   # crucially, the misc08 mount must be available before the UCSC Genome
#   # browser VM is deployed
  # import_playbook: sn10.yml

- name: Manage UCSC Genome Browser VM
  # provisional deployment, to be replaced either by a bare-metal or a
  # Terraform-based virtual machine
  hosts: sn10
  become: true
  vars:
    ucsc_genome_browser_ansible_group: ucsc_genome_browser
  vars_files:
    - group_vars/ucsc_genome_browser/vars.yml
    - group_vars/ucsc_genome_browser/vault.yml
  pre_tasks:
    - name: Install Vagrant
      block:
        - name: Install yum-utils
          ansible.builtin.package:
            name: yum-utils
            state: present

        - name: Import HashiCorp GPG key
          ansible.builtin.rpm_key:
            state: present
            key: https://rpm.releases.hashicorp.com/gpg

        - name: Add HashiCorp YUM repository
          ansible.builtin.yum_repository:
            name: hashicorp
            description: HashiCorp Stable - $basearch
            baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
            enabled: true
            gpgcheck: true
            gpgkey: "https://rpm.releases.hashicorp.com/gpg"
            state: present

        - name: Install `vagrant` package
          ansible.builtin.dnf:
            name: vagrant
            state: present
            update_cache: true

        - name: Install QEMU and Vagrant libvirt plugin
          block:
            - name: Ensure KVM, `libvirt` and QEMU are available
              ansible.builtin.package:
                name:
                  - qemu-kvm
                  - libvirt
                state: present

            - name: Enable and start all modular Libvirt sockets
              ansible.builtin.systemd:
                name: "{{ item }}"
                state: started
                enabled: true
              with_items:
                - virtqemud.socket
                - virtnetworkd.socket
                - virtstoraged.socket
                - virtnodedevd.socket
                - virtnwfilterd.socket
                - virtsecretd.socket
                - virtinterfaced.socket
                # - virtproxyd.socket
              become: true

            - name: Check if Vagrant libvirt plugin is already installed
              ansible.builtin.command:
                cmd: vagrant plugin list
              register: vagrant_plugins
              changed_when: false

            - name: Install build dependencies for Vagrant libvirt plugin
              ansible.builtin.package:
                name:
                  - make
                  - gcc
                  - libvirt-devel
                state: present
                enablerepo: crb
              when: "'vagrant-libvirt' not in vagrant_plugins.stdout"

            - name: Build Vagrant libvirt plugin
              ansible.builtin.command:
                cmd: vagrant plugin install vagrant-libvirt
              register: vagrant_plugin_install
              failed_when: vagrant_plugin_install.rc != 0
              when: "'vagrant-libvirt' not in vagrant_plugins.stdout"
  tasks:
    - name: Manage UCSC Genome Browser VM
      block:
        - name: Gather system service facts
          ansible.builtin.service_facts:

        - name: Ensure UCSC Genome Browser Vagrant project directory exists
          ansible.builtin.file:
            path: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}"
            state: directory
            owner: root
            group: root
            mode: "0750"

        - name: Deploy Vagrantfile for UCSC Genome Browser VM
          ansible.builtin.copy:
            dest: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}/Vagrantfile"
            content: "{{ ucsc_genome_browser_vm_vagrantfile }}"

        - name: Open forwarded ports for UCSC Genome Browser VM
          ansible.posix.firewalld:
            port: "{{ port }}/tcp"
            immediate: true
            permanent: true
            state: enabled
          loop: "{{ ucsc_genome_browser_vm_ports | map(attribute='host') | list }}"
          loop_control:
            loop_var: port
          when:
            - ucsc_genome_browser_vm_state == "present"
            - "'firewalld.service' in ansible_facts.services"

        - name: Start UCSC Genome Browser VM
          when: ucsc_genome_browser_vm_state == "present"
          ansible.builtin.command:
            cmd: vagrant up
            chdir: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}"

        - name: Destroy UCSC Genome Browser VM
          when: ucsc_genome_browser_vm_state == "absent"
          ansible.builtin.command:
            cmd: vagrant destroy -f
            chdir: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}"

        - name: Clear UCSC Genome Browser Vagrant project directory
          when: ucsc_genome_browser_vm_state == "absent"
          ansible.builtin.file:
            path: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}"
            state: absent

        - name: Close forwarded ports for UCSC Genome Browser VM
          ansible.posix.firewalld:
            port: "{{ port }}/tcp"
            immediate: true
            permanent: true
            state: disabled
          loop: "{{ ucsc_genome_browser_vm_ports | map(attribute='host') | list }}"
          loop_control:
            loop_var: port
          when:
            - ucsc_genome_browser_vm_state == "absent"
            - "'firewalld.service' in ansible_facts.services"
  post_tasks:
    - name: Retrieve IP address for UCSC Genome Browser VM
      when: ucsc_genome_browser_vm_state == "present"
      block:
        - name: Get IP address for UCSC Genome Browser VM
          ansible.builtin.shell:
            cmd: vagrant ssh-config | grep HostName | awk '{print $2}'
            chdir: "{{ ucsc_genome_browser_vm_vagrant_project_dir }}"
          register: ucsc_genome_browser_vm_ip_address
          changed_when: false

        - name: Write hostname for UCSC Genome Browser VM to hosts file
          vars:
            ucsc_genome_browser_host_entry_tag: "UCSC Genome Browser VM"
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: ".*# {{ ucsc_genome_browser_host_entry_tag }}$"
            line: "{{ ucsc_genome_browser_vm_ip_address.stdout }} {{ groups[ucsc_genome_browser_ansible_group][0] }}  # {{ ucsc_genome_browser_host_entry_tag }}"
            state: "{{ ( ucsc_genome_browser_vm_state == 'present' ) | ternary('present', 'absent') }}"

- name: Install UCSC Genome Browser
  hosts: ucsc_genome_browser
  tags: ucsc_genome_browser
  roles:
    - name: usegalaxy_eu.ucsc_genome_browser
      become: true
  tasks:
    - name: Symlink databases in UCSC Genome Browser database meta directory
      become: true
      # TODO: move block into an Ansible module, inspiration can be taken from
      # https://github.com/galaxyproject/ansible-galaxy/blob/c4eefedde405bfa8fe5e55899f8e851986b5aa5f/library/symlink_clone.py
      # but please note the logic is different (in this case, directories are
      # actually symlinked).
      block:
        - name: Get all symlinks in MariaDB directory
          ansible.builtin.find:
              paths: "/var/lib/mysql/"
              file_type: link
              hidden: false
          register: ucsc_genome_browser_vm_mariadb_contents_links

        - name: Get all directories in UCSC Genome Browser database meta directory
          ansible.builtin.find:
            paths: "{{ ucsc_genome_browser_vm_gbd_dir }}/meta/"
            file_type: directory
            hidden: false
          register: ucsc_genome_browser_vm_gbd_dir_meta_contents_directories

        - name: Get all links in UCSC Genome Browser database meta directory
          ansible.builtin.find:
            paths: "{{ ucsc_genome_browser_vm_gbd_dir }}/meta/"
            file_type: link
            hidden: false
          register: ucsc_genome_browser_vm_gbd_dir_meta_contents_links

        - name: Map expected symlinks in MariaDB directory to their expected sources
          ansible.builtin.set_fact:
            ucsc_genome_browser_vm_mariadb_symlink_map: >-
              {{
                ucsc_genome_browser_vm_mariadb_symlink_map | default({}) | combine({
                  '/var/lib/mysql/' ~ (item.path | basename): item.path
                })
              }}
          loop: "{{ ucsc_genome_browser_vm_gbd_dir_meta_contents_directories.files + ucsc_genome_browser_vm_gbd_dir_meta_contents_links.files }}"
          loop_control:
            label: "{{ item.path | basename }}"
          when:
            - (item.path | basename) not in ['hgcentral', 'hgTemp']

        - name: Run `stat` on symlink target paths in MariaDB directory
          ansible.builtin.stat:
            path: "/var/lib/mysql/{{ item.key | basename }}"
          loop: "{{ ucsc_genome_browser_vm_mariadb_symlink_map | dict2items }}"
          loop_control:
            label: "{{ item.key }}"
          register: ucsc_genome_browser_vm_mariadb_contents_hg_paths_stat

        - name: Remove incorrect files/directories/links in MariaDB directory
          ansible.builtin.file:
            path: "/var/lib/mysql/{{ item.stat.path | basename }}"
            state: absent
          loop: "{{ ucsc_genome_browser_vm_mariadb_contents_hg_paths_stat.results }}"
          loop_control:
            label: "{{ item.item.key | basename }}"
          vars:
            intended_source: "{{ expected_symlink_map[item.stat.path] }}"
          when:
            - item.stat.exists
            - (not item.stat.islnk) or (item.stat.lnk_source != intended_source)

        - name: Create symlinks in MariaDB directory
          # TODO: symlinks should also be removed when the source files are removed
          ansible.builtin.file:
              src: "{{ item.value }}"
              dest: "/var/lib/mysql/{{ item.key | basename }}"
              state: link
          loop: "{{ ucsc_genome_browser_vm_mariadb_symlink_map | dict2items }}"
          loop_control:
              label: "{{ item.key | basename }}"

    - name: Ensure DBs as symbolic-links are enabled in MariaDB configuration
      become: true
      community.general.ini_file:
        path: /etc/my.cnf.d/mariadb-server.cnf
        section: mariadb
        option: symbolic-links
        value: "1"
