---
- name: Install and configure tusd
  hosts: upload
  become: true
  become_user: root
  vars:
    upload_dir_test: /data/jwd03f/tus_upload/test
    upload_dir_main: /data/jwd03f/tus_upload/main
    tusd_instances:
      - name: test_uploads
        # user that tusd will run as
        user: "{{ user_name }}"
        # group that tusd will run as
        group: "{{ user_group_name }}"
        # args passed to tusd
        args:
          - -host=upload.galaxyproject.eu
          - -port=1080
          - "-upload-dir={{ upload_dir_test }}"
          - -hooks-http=https://test.usegalaxy.eu/api/upload/hooks
          - -hooks-http-forward-headers=X-Api-Key,Cookie
      - name: main_uploads
        # user that tusd will run as
        user: "{{ user_name }}"
        # group that tusd will run as
        group: "{{ user_group_name }}"
        # args passed to tusd
        args:
          - -host=upload.galaxyproject.eu
          - -port=1081
          - "-upload-dir={{ upload_dir_main }}"
          - -hooks-http=https://usegalaxy.eu/api/upload/hooks
          - -hooks-http-forward-headers=X-Api-Key,Cookie

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
        enable_create_user: true
        enable_kernel_5: true
        enable_install_software: true
    - influxdata.chrony
    ## Filesystems
    - usegalaxy-eu.autofs     # Setup the mount points which will be needed later

    - galaxyproject.tusd
