---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- ansible.builtin.include_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

- ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'


# HXR: Ensure user is part of ssl-cert group and will have access to that data.
- name: Add user to ssl-cert
  user:
    name: "{{ __nginx_user }}"
    groups: ssl-cert
    append: yes
  when: ssl_cert_group_available is defined and ssl_cert_group_available

# Vhost configuration.
- ansible.builtin.include_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
