---
- name: autofs package install
  package:
    name: autofs
    state: latest

- name: Copy main autofs file
  template:
    src: data.autofs.j2
    dest: "/etc/auto.master.d/data.autofs"
    owner: root
    group: root
    mode: 0644
  notify: autofs restart

- name: Copy data conf file
  template:
    src: "data.conf.j2"
    dest: "/etc/auto.data"
    owner: root
    group: root
    mode: 0644
  notify: autofs restart

- name: Copy discontinued conf file
  template:
    src: "discontinued.conf.j2"
    dest: "/etc/auto.discontinued"
    owner: root
    group: root
    mode: 0644
  when: '"discontinued" in usegalaxy_eu_autofs_mounts'
  notify: autofs restart

- name: Copy usrlocal conf file
  template:
    src: "usrlocal.conf.j2"
    dest: "/etc/auto.usrlocal"
    owner: root
    group: root
    mode: 0644
  when: '"usrlocal" in usegalaxy_eu_autofs_mounts'
  notify: autofs restart

- name: Copy vols conf file
  template:
    src: "vols.conf.j2"
    dest: "/etc/auto.vols"
    owner: root
    group: root
    mode: 0644
  when: '"vdb" in usegalaxy_eu_autofs_mounts'
  notify: autofs restart

- name: autofs service enable
  service:
    name: autofs
    enabled: yes
    state: started

- name: Flush handlers to ensure mounts are available
  meta: flush_handlers
