---
#- include_tasks: account.yml
  #when: grt_create_group or grt_create_user
- name: Include user tasks
  include_tasks: user.yml
  when: grt_create_user

- name: Include directory setup tasks
  include_tasks: dirs.yml

- name: Clone repository
  git:
    repo: "https://github.com/erasche/galactic-radio-telescope"
    dest: "{{ grt_dir }}/code/"
    version: "{{ grt_version }}"
    force: "{{ grt_force_checkout }}"
  register: repo_cloned
  notify: 'reload grt'

- name: Include dependency installation tasks
  include_tasks: dependencies.yml

- name: Include Django setup tasks
  include_tasks: django.yml
  when: repo_cloned.changed

- name: Include configuration tasks
  include_tasks: config.yml

- name: Include systemd tasks
  include_tasks: systemd.yml

- name: Include cron tasks
  include_tasks: cron.yml
