---
- name: Send runner script
  ansible.builtin.template:
    src: "run.sh"
    dest: "{{ grt_dir }}/run.sh"
    owner: "{{ grt_user.name }}"
    group: "{{ grt_group.name }}"
    mode: 0750
  notify: 'reload grt'

- name: Install systemd unit file
  ansible.builtin.template:
    src: grt.service
    dest: /etc/systemd/system/galactic-radio-telescope.service
    mode: "0644"
  notify: setup grt systemd
