---
# valkey
valkey_port: 6379
valkey_bind_interface: 0.0.0.0
valkey_rdbcompression: "yes"
valkey_dbfilename: dump.rdb
valkey_dbdir: /var/lib/valkey
valkey_loglevel: "notice"
valkey_logfile: /var/log/valkey/valkey.log
valkey_databases: 16
valkey_appendonly: "no"
valkey_appendfsync: "everysec"
valkey_save:
  - 900 1
  - 300 10
  - 60 10000
