#!/bin/bash
export VAULT_ADDR=${1:-https://vault.usegalaxy.eu}
VAULT_AUTH_USER=${2:-openstack}
VAULT_AUTH_PASS=${3:-password}

# Login to vault server
vault login -method=userpass username=$VAULT_AUTH_USER password=$VAULT_AUTH_PASS

# ensure there's a newline, sometimes there isn't.
echo "" >> /etc/ssh/sshd_config

# Then loop over every key.
for i in /etc/ssh/ssh*key.pub; do
	# Original key file
	keyfile=/etc/ssh/$(basename $i .pub);
	# Output ceritifcate
	outfile=/etc/ssh/$(basename $i .pub)-cert.pub;
	# Sign the key and write out
	vault write -field=signed_key ssh-host-signer/sign/hostrole cert_type=host public_key=@$i > $outfile;
	# Should be root:root 0640
	chmod 640 $outfile;
	chown root:root $outfile;
	# And need to mention in config
	sed -i "s|HostKey $keyfile|HostKey $keyfile\nHostCertificate $outfile|" /etc/ssh/sshd_config;
done;

# Also load CA certificate for trusting user keys
vault read -field=public_key ssh-client-signer/config/ca > /etc/ssh/trusted-user-ca-keys.pem
sed -i "s|HostKey /etc/ssh/ssh_host_rsa_key|TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem\nHostKey /etc/ssh/ssh_host_rsa_key|" /etc/ssh/sshd_config
# and restart
systemctl restart sshd
