---
- name: Set Certbot script variable.
  set_fact:
    certbot_cmd_environment: "--test-cert"
  when: certbot_environment == 'staging'

- name: Set Certbot script variable when not staging.
  set_fact:
    certbot_cmd_environment: ""
  when: certbot_environment != 'staging'

- name: Request certificate
  command: |
      certbot
        certonly
        {{ certbot_cmd_environment }}
        --non-interactive
        {% if certbot_dns_provider is defined %}
        --dns-{{ certbot_dns_provider }}
        {% else %}
        {{ certbot_auth_method | default("--standalone") }}
        {% endif %}
        -m {{ certbot_admin_email }}
        {{ certbot_agree_tos }}
        -d {{ ','.join(certbot_domains) }}
  register: request
  creates: "/etc/letsencrypt/renewal/{{ certbot_hostname_override | default(certbot_domains[0]) }}.conf"

- name: Output of command
  debug: var=request
