---
- name: Reload systemd for annual Galaxy cleanup
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart annual Galaxy cleanup timer
  ansible.builtin.systemd:
    name: "{{ galaxy_cleanup_force_retry_timer }}"
    state: restarted
