---
- name: "Checkout matching OSIRIS version"
  ansible.builtin.git:
    repo: "{{ osiris_repo }}"
    dest: "{{ osiris_www_dir }}"
    version: "{{ osiris_version }}"
    update: true
  become: yes
  become_user: "apache"
  environment:
    ANSIBLE_SYSTEM_WARNINGS: "False"
  vars:
    # Prevent ansible from using $HOME/.ansible/tmp
    # which for 'apache' is /usr/share/httpd/.ansible/tmp
    ansible_remote_tmp: /tmp/ansible_osiris_checkout

- name: "Ensure permissions for OSIRIS PHP files"
  ansible.builtin.file:
    path: "{{ osiris_www_dir }}"
    owner: "apache"
    group: "apache"
    mode: "u=rwX,g=rwX,o="
    recurse: true
    state: directory
