http:
  serversTransports:
    apollo-transport:
      forwardingTimeouts:
        idleConnTimeout: 300s
  services:
    apollo:
      loadBalancer:
        serversTransport: apollo-transport
        servers:
          - url: "http://apollo.internal.galaxyproject.eu"
