http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
  routers:
    http-catchall-rtr:
      rule: Host(`*`)
      service: noop@internal
      entryPoints:
        - web
      middlewares:
        - redirect-https
