http:
  routers:
    jenkins-rtr:
      rule: "Host(`build.galaxyproject.eu`)"
      service: jenkins
      entryPoints:
        - websecure
        - web
      tls:
        certResolver: "route53"
        domains:
          - main: "build.galaxyproject.eu"
      middlewares:
        - https-redirect
