http:
  routers:
    plausible-rtr:
      rule: "Host(`plausible.galaxyproject.eu`)"
      service: plausible
      entryPoints:
        - websecure
        - web
      tls:
        certResolver: "route53"
        domains:
          - main: "plausible.galaxyproject.eu"
      middlewares:
        - https-redirect
        - plausible-allow-iframe
