http:
  routers:
    usegalaxy-eu-sse-rtr:
      rule: "Host(`*.usegalaxy.eu`) && PathPrefix(`/api/events/stream`)"
      entryPoints:
        - websecure
        - web
      service: usegalaxy-eu-sse
      middlewares:
        - https-redirect
