http:
  middlewares:
    stats-compress:
      compress:
        excludedContentTypes:
          - image/png
          - image/jpeg
          - image/gif
          - application/zip
          - application/gzip
