http:
  routers:
    grafana-rtr:
      rule: "Host(`stats.galaxyproject.eu`)"
      service: grafana
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "stats.galaxyproject.eu"
