http:
  routers:
    ucsc-genome-browser-rtr:
      rule: "Host(`genome-browser.galaxyproject.eu`)"
      service: ucsc-genome-browser
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "genome-browser.galaxyproject.eu"
