---
- name: "Check if user {{ target_user }} exists on target host"
  ansible.builtin.set_fact:
    user_exists: "{{ target_user in (getent_passwd_result.ansible_facts.getent_passwd | default({})).keys() }}"

- name: "Process user {{ target_user }}"
  become: true
  become_user: "{{ target_user }}"
  block:
    - name: "Ensure ~/.ssh directory exists for {{ target_user }}"
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: "0700"

    - name: "Manage SSH keys for {{ target_user }}"
      ansible.posix.authorized_key:
        user: "{{ target_user }}"
        key: "{{ user_keys_map[target_user] | join('\n') }}"
        state: present
        exclusive: true
  when:
    - user_exists | bool
    - user_keys_map[target_user] | default([]) | length > 0

- name: "Warning for non-existent user {{ target_user }}"
  ansible.builtin.debug:
    msg: "Warning: User {{ target_user }} does not exist on {{ inventory_hostname }}, skipping"
  when: not (user_exists | bool)
