---
- name: "Process role: {{ current_role.name }}"
  ansible.builtin.debug:
    msg: "Processing role {{ current_role.name }} for host {{ target_host | default(inventory_hostname) }}"

- name: "Collect SSH keys for role: {{ current_role.name }}"
  ansible.builtin.set_fact:
    role_keys: >-
      {{ ssh_users
         | selectattr('roles', 'contains', current_role.name)
         | map(attribute='key')
         | flatten
         | reject('match', '^https?://')
         | list }}
  delegate_to: "{{ target_host | default(omit) }}"

- name: "Collect SSH keys from URLs for role: {{ current_role.name }}"
  ansible.builtin.set_fact:
    role_url_keys: >-
      {{ ssh_users
         | selectattr('roles', 'contains', current_role.name)
         | map(attribute='key')
         | flatten
         | select('match', '^https?://')
         | list }}
  delegate_to: "{{ target_host | default(omit) }}"



- name: "Fetch keys from URLs for role: {{ current_role.name }}"
  ansible.builtin.set_fact:
    fetched_keys: >-
      {{ fetched_keys | default([]) + (
           lookup('url', item) 
           | default('') 
           | replace(',', '\n')
           | split('\n') 
           | map('trim') 
           | reject('equalto', '') 
           | select('match', '^(ssh-rsa|ssh-dss|ssh-ed25519|ecdsa-sha2-|sk-ssh-ed25519@openssh.com|sk-ecdsa-sha2-)') 
           | list
         ) }}
  loop: "{{ role_url_keys | default([]) | unique }}"
  when: role_url_keys | default([]) | length > 0
  delegate_to: "{{ target_host | default(omit) }}"



- name: "Combine all keys for role: {{ current_role.name }}"
  ansible.builtin.set_fact:
    all_role_keys: >-
      {{ (role_keys | default([])) + (fetched_keys | default([])) 
         | map('trim') 
         | reject('equalto', '') 
         | unique 
         | list }}
  delegate_to: "{{ target_host | default(omit) }}"



- name: "Add role keys to each target user in user_keys_map"
  ansible.builtin.set_fact:
    user_keys_map: >-
      {{ user_keys_map | combine({
           item: (user_keys_map.get(item, []) + all_role_keys) | unique | list
         }) }}
  loop: "{{ current_role.users }}"
  when: 
    - current_role.users is defined
    - current_role.users | length > 0
    - all_role_keys | length > 0
  delegate_to: "{{ target_host | default(omit) }}"

- name: "Reset variables for next role"
  ansible.builtin.set_fact:
    role_keys: []
    role_url_keys: []
    fetched_keys: []
    all_role_keys: []
  delegate_to: "{{ target_host | default(omit) }}"