---

- name: Initialize user_keys_map entry for {{ user_account }} if missing
  ansible.builtin.set_fact:
    user_keys_map: "{{ user_keys_map | default({}) | combine({ user_account: (user_keys_map[user_account] | default([])) }) }}"
  delegate_to: "{{ target_host | default(omit) }}"

- name: Loop over user's URL list and append fetched keys
  ansible.builtin.set_fact:
    user_keys_map: >-
      {{
        user_keys_map
        | default({})
        | combine({
            user_account: (
              (user_keys_map[user_account] | default([]))
              + (
                  lookup('url', url_item)
                  | default('')
                  | split(',')
                )
            )
        })
      }}
  loop: "{{ user_url_list }}"
  loop_control:
    loop_var: url_item
  delegate_to: "{{ target_host | default(omit) }}"
