# fixed tasks for root account management
- name: Ensure .ssh directory exists for root
  become: true
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'
  delegate_to: "{{ target_host | default(omit) }}"

- name: Add Keys to Github
  become: false
  ansible.builtin.set_fact:
    root_keys_list: >-
      {{ ssh_users
         | selectattr('roles','contains','root')
         | map(attribute='key')
         | flatten
         | reject('match', '^https://')
         | list }}
  delegate_to: "{{ target_host | default(omit) }}"

- name: Append keys fetched from Github
  become: false
  ansible.builtin.set_fact:
    root_keys_list: >-
      {{
        root_keys_list +
        (
          lookup('url', item)
          | default('')
          | split(',')
        )
      }}
  loop: "{{ ssh_users | selectattr('roles','contains','root') | map(attribute='key') | flatten | select('match','^https://') | list }}"
  when: (ssh_users | selectattr('roles','contains','root') | map(attribute='key') | flatten | select('match','^https://') | list) | length > 0
  delegate_to: "{{ target_host | default(omit) }}"

- name: Deduplicate root_keys_list
  become: false
  ansible.builtin.set_fact:
    root_keys_list: "{{ root_keys_list | default([]) | unique | list }}"
  delegate_to: "{{ target_host | default(omit) }}"

- name: Write /root/.ssh/authorized_keys
  become: true
  ansible.builtin.copy:
    dest: /root/.ssh/authorized_keys
    content: "{{ (root_keys_list | default([])) | join('\n') + (root_keys_list | length > 0 and '\n' or '') }}"
    owner: root
    group: root
    mode: '0600'
  delegate_to: "{{ target_host | default(omit) }}"
