---
monitor_condor_split_util: false
monitor_condor: false
monitor_sge: false
monitor_slurm: false
condor_hosts_inventory_url: https://raw.githubusercontent.com/usegalaxy-eu/vgcn-infrastructure-playbook/main/hosts
