---
- name: "Deploy error pages"
  template:
    src: error.html.j2
    dest: "{{ error_pages_dest }}/{{ item.code }}.html"
    owner: "{{ error_pages_owner }}"
    group: "{{ error_pages_group }}"
    mode: 0644
  loop: "{{ error_pages }}"
  loop_control:
    label: "{{ item.code }}.html"
