---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'infrastructure-playbook'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'infrastructure-playbook'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            infrastructure-playbook/requirements.txt
            infrastructure-playbook/.github/requirements-python-lint.txt

      - name: Cache Ansible Galaxy content
        uses: actions/cache@v4
        with:
          path: |
            infrastructure-playbook/roles
            infrastructure-playbook/collections
          key: ${{ runner.os }}-ansible-galaxy-${{ hashFiles('infrastructure-playbook/requirements.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-galaxy-

      - name: Install test dependencies.
        run: |
          pip3 install -r requirements.txt
          pip3 install -r .github/requirements-python-lint.txt

      - name: Create fake vault password file.
        run: printf '%s\n' 'fake_password' > .vault_password

      - name: Validate repository.
        run: make 
